const styles = () => ({
  appBody: {
    fontFamily: "Airbnb Cereal App Light",
    display: "flex",
    flexDirection: "column",
    // maxWidth: "80vw",
  },
  // marqueeApp: {
  //   width: "80vw",
  //   height: "80vh",
  // },
  marqueeDescriptionModal: {
    width: "80%",
    height: "60%",
    // width: 600,
    // height: 400,
    position: "absolute",
    top: 100,
    bottom: 0,
    left: 0,
    right: 0,
    margin: "auto",
    background: "seashell",
  },
  marqueeSleepingCard: {
    width: 150,
    height: 125,
    borderRadius: "10%",
    border: "1px solid lightgray",
    margin: 5,
  },
  marqueeSleepingFlexbox: {
    display: "flex",
  },
  marqueeReadDescriptionButton: {
    fontWeight: "bold",
  },
  // marqueeSubmodulesDiv: {
  //   width: 600,
  // },
  photoBox: {
    display: "flex",
    flexDirection: "rows",
    width: "100%",
    // gridTemplateRows: "1fr 1fr",
    // maxWidth: 600,
  },
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    height: "auto",
    // gridTemplateColumns: "250px 250px 250px 250px",
    // gridTemplateRows: "250px 250px",
    // width: "100vw",
    // height: "100vh",
  },
  photoItem: {
    margin: "2.5px",
    // width: "50%",
    // height: "50%",
    height: 200,
    // width: "auto",
    // width: 274,
    width: 240,
    // height: 240,
    objectFit: "cover",
  },
  // marqueeImage: {
  //   maxWidth: "100vw",
  //   // maxWidth: "100%",
  //   // objectFit: "cover",
  // },
  mainPhotoItem: {
    // gridColumnStart: 1,
    // gridColumnEnd: 3,
    // gridRowStart: 1,
    // gridRowEnd: 2,
    margin: 5,
    // width: "60vw",
    // height: "60vh",
    height: 400,
    // height: "auto",
    width: "50%",
    // width: 564,
    // width: 490,
    // height: 490,
    objectFit: "cover",
  },
  // itemA: {
  //   maxWidth: 50,
  //   maxHeight: 50,
  //   // gridColumnStart: 3,
  //   // gridColumnEnd: 4,
  //   // gridRowStart: 1,
  //   // gridRowEnd: 2,
  //   background: "rgb(184, 184, 247)",
  // },
  // itemB: {
  //   maxWidth: 50,
  //   maxHeight: 50,
  //   // gridColumnStart: 4,
  //   // gridColumnEnd: 4,
  //   // gridRowStart: 1,
  //   // gridRowEnd: 2,
  //   background: "rgb(241, 241, 245)",
  // },
  // itemC: {
  //   maxWidth: 50,
  //   maxHeight: 50,
  //   // gridColumnStart: 3,
  //   // gridColumnEnd: 4,
  //   // gridRowStart: 2,
  //   // gridRowEnd: 2,
  // },
  // itemD: {
  //   maxWidth: 50,
  //   maxHeight: 50,
  //   // gridColumnStart: 4,
  //   // gridColumnEnd: 4,
  //   // gridRowStart: 2,
  //   // gridRowEnd: 2,
  // },
  photoButton: {
    gridColumnStart: 4,
    gridRowStart: 2,
    position: "relative",
    top: 180,
    left: 40,
    height: 30,
    width: 160,
  },
  marqueePhotoModalGridlist: {
    // width: "50%",
    // marginLeft: 500,
    // marginRight: "auto",
  },
  // marqueePhotoModal: {
  //   display: "flex",
  //   justifyContent: "center",
  //   background: "white",
  //   // position: "absolute",
  //   height: "100vh",
  //   width: "100vw",
  // },
  // marqueePhotoModalBackButton: {
  //   display: "block",
  //   position: "absolute",
  //   left: 10,
  //   top: 10,
  //   height: 50,
  //   width: 50,
  //   borderRadius: "50%",
  //   border: "none",
  // },
});

export default styles;
