version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node
      - image: circleci/mongo:4.1.9
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'seed db'
          command: npm run seed
      - run:
          name: 'Running tests'
          command: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Running lint'
          command: npm run lint
workflows:
  run-tests:
    jobs:
      - lint
      - test